### ISSUE TITLE
Superimposed Stomach Mesh

### ISSUE THREAD

**Issue by ParabolicSamuel** [Vicyntae/SCV#6]
Your latest update with the Serpent Stone fix seems to have created a superimposed stomach on the player. I have isolated it to SCV since it doesn't happen with only SCL installed. I also noticed that with SCV installed, that _dynamic equipment_ is set to default instead of _nioverride_. Tested with both my standard playthrough and a testing profile with only the required mods to run SCL. Both profiles causing stomach glitch.
A picture has been included to give idea. 

![elder scrolls v skyrim screenshot 2018 05 20 - 23 18 30 82](https://user-images.githubusercontent.com/34223279/40289113-87ff1d2c-5c84-11e8-9647-22ead7fb4ee0.png)

**Comment by Vicyntae** [comment]
Okay, it's not actually a *glitch* per-say. Dynamic Equipment puts a fake belly mesh over actor's abdomen which grows and shrinks with the actor's fullness, negating the need for a belly node on the skeleton or any specialized mesh building, since skeletal scaling is rather finicky and tends to produce mediocre results. If you set it to nioverride, it should disappear. I'll probably rebuild the meshes again at some point so that they don't peak through clothing prematurely.

**Comment by ParabolicSamuel** [comment]
Thanks for explaining, I had no idea.
